name: Create/Update AWS Task Definition

on:
  workflow_dispatch:  # This event allows manual triggering
  
env:
  AWS_REGION: us-east-1
  AWS_TASK_DEFINITION: SQUID_HTTP_PROXY_V2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @aws-sdk/client-ecs @aws-sdk/credential-providers

      - name: Create Task Definition
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_TASK_DEFINITION: ${{ env.AWS_TASK_DEFINITION }}
          SQUID_USERNAME: ${{ secrets.SQUID_USERNAME }}
          SQUID_PASSWORD: ${{ secrets.SQUID_PASSWORD }}
          CLOUDFLARE_DNS: ${{ secrets.CLOUDFLARE_DNS }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          NO_IP_USERNAME: ${{ secrets.NO_IP_USERNAME }}
          NO_IP_PASSWORD: ${{ secrets.NO_IP_PASSWORD }}
          NO_IP_HOSTNAME: ${{ secrets.NO_IP_HOSTNAME }}
        run: node aws/create-task-definition.js