name: Stop Task Definition on AWS ECS

on:
  workflow_dispatch:  # This event allows manual triggering
  
env:
  AWS_REGION: us-east-1
  AWS_CLUSTER_NAME: TestClusterV1
  AWS_TASK_DEF: SQUID_HTTP_PROXY_V2
  
# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Stop Task Definition
      run: |
        first_task_arn=$(aws ecs list-tasks --cluster "$AWS_CLUSTER_NAME" --family "$AWS_TASK_DEF" --query "taskArns[0]" --output text)
        echo $first_task_arn
        
        aws ecs stop-task --cluster "$AWS_CLUSTER_NAME" --task "$first_task_arn" --output text
