name: Stop Task Definition on AWS ECS

on:
  workflow_dispatch:  # This event allows manual triggering
  
env:
  AWS_REGION: us-east-1
  AWS_CLUSTER_NAME: TestClusterV1
  AWS_TASK_DEFINITION: SQUID_HTTP_PROXY_V2
  
# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @aws-sdk/client-ecs @aws-sdk/credential-providers

      - name: Stop Task Definition on ECS Cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_CLUSTER_NAME: ${{ env.AWS_CLUSTER_NAME }}
          AWS_TASK_DEFINITION: ${{ env.AWS_TASK_DEF }}
        run: node aws/stop-task-definition.js
